variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_1_cidr" {}
variable "private_subnet_2_cidr" {}
variable "az1" {}
variable "az2" {}
variable "bastion_ip" {}
variable "bastion_ami" {}
variable "nginx_ami" {}
variable "bastion_instance_type" {}
variable "nginx_instance_type" {}
